name 'base-oracle-db'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures base-oracle-db'
long_description 'Installs/Configures base-oracle-db'
version '0.1.0'

depends 'hostsfile'
depends 'sudo'
